Repository puppetlabs/puppetlabs-chocolatey, pull requests merged in 2019-07, with the labels that each got.

#159 (MODULES-9310) Raise lower Puppet bound to 5.5.10
  metadata.json
Labels: backwards-incompatible

#162 (MODULES-9317) Add Puppet Strings docs
  README.md
  REFERENCE.md
  lib/puppet/provider/chocolateyconfig/windows.rb
  lib/puppet/provider/chocolateyfeature/windows.rb
  lib/puppet/provider/chocolateysource/windows.rb
  lib/puppet/type/chocolateyconfig.rb
  lib/puppet/type/chocolateyfeature.rb
  lib/puppet/type/chocolateysource.rb
  lib/puppet_x/chocolatey/chocolatey_common.rb
  lib/puppet_x/chocolatey/chocolatey_install.rb
  lib/puppet_x/chocolatey/chocolatey_version.rb
  manifests/config.pp
  manifests/init.pp
  manifests/install.pp
  manifests/params.pp
Labels: feature

#160 (maint) Update issues url
  metadata.json
Labels: maintenance

#161 (MODULES-9307) Convert mocha tests to rspec-mocks
  .sync.yml
  .travis.yml
  metadata.json
  spec/classes/config_spec.rb
  spec/classes/coverage_spec.rb
  spec/classes/init_spec.rb
  spec/classes/install_spec.rb
  spec/spec_helper.rb
  spec/unit/facter/choco_install_path_spec.rb
  spec/unit/facter/choco_temp_dir.rb
  spec/unit/facter/chocolateyversion_spec.rb
  spec/unit/puppet/provider/chocolateyconfig/windows_spec.rb
  spec/unit/puppet/provider/chocolateyfeature/windows_spec.rb
  spec/unit/puppet/provider/chocolateysource/windows_spec.rb
  spec/unit/puppet/provider/package/chocolatey_spec.rb
  spec/unit/puppet/type/chocolateyconfig_spec.rb
  spec/unit/puppet/type/chocolateyfeature_spec.rb
  spec/unit/puppet/type/chocolateysource_spec.rb
  spec/unit/puppet_x/chocolatey/chocolatey_common_spec.rb
  spec/unit/puppet_x/chocolatey/chocolatey_install_spec.rb
  spec/unit/puppet_x/chocolatey/chocolatey_version_spec.rb
Labels: maintenance

#156 (FM-8194) Convert tests to litmus
  .fixtures.yml
  .rubocop.yml
  .sync.yml
  Gemfile
  README.md
  Rakefile
  appveyor.yml
  distelli-manifest.yml
  provision.yaml
  spec/acceptance/config_values_spec.rb
  spec/acceptance/features_spec.rb
  spec/acceptance/package_spec.rb
  spec/acceptance/sources_spec.rb
  spec/spec_helper_acceptance.rb
  spec/spec_helper_acceptance_local.rb
  spec/support/backup_and_reset_config_context.rb
  spec/support/examples/failing_manifest.rb
  spec/support/examples/manifest_removes_value.rb
  spec/support/examples/password_value_should_be.rb
  spec/support/examples/successful_config_change.rb
  spec/support/scripts/backup_config.ps1
  spec/support/scripts/reset_config.ps1
  spec/support/utilities/helpers.rb
Labels: feature

#163 (MODULES-9614) dependencychecker - update stdlib version
  metadata.json
Labels: maintenance

#164 (maint) update .sync.yaml file and pdk update
  .sync.yml
  metadata.json
Labels: maintenance
