Repository puppetlabs/puppetlabs-chocolatey, pull requests merged in 2020-08, with the labels that each got.

#219 pdksync - (IAC-973) - Update travis/appveyor to run on new default branch `main`
  .travis.yml
  Rakefile
  appveyor.yml
  metadata.json
Labels: feature

#224 (IAC-980) - Removal of inappropriate terminology
  .github/workflows/release.yml
  .github/workflows/weekly.yml
  .repo/config
  CHANGELOG.md
  CONTRIBUTING.md
  HISTORY.md
  README.md
  metadata.json
Labels: feature

#226 (maint) - version 5.1.0 merge back
  CHANGELOG.md
  REFERENCE.md
  metadata.json
Labels: maintenance

#227 (maint) - Removing bolt gem pin
  Gemfile
Labels: maintenance

#228 (MODULES-10791) Increase upper boundary for powershell dependency to 5.0.0
  metadata.json
Labels: bugfix

#229 (MODULES-10793) Release MergeBack v5.1.1
  CHANGELOG.md
  metadata.json
Labels: maintenance
