Repository puppetlabs/puppetlabs-chocolatey, pull requests merged in 2021-02, with the labels that each got.

#248 pdksync - Remove Puppet 5 from testing and bump minimal version to 6.0.0
  .github/workflows/auto_release.yml
  .rubocop.yml
  .sync.yml
  .travis.yml
  appveyor.yml
  metadata.json
Labels: backwards-incompatible

#249 (maint) Update major dependencies prior to release
  metadata.json
Labels: maintenance

#247 (MODULES-10704) - Have the code error out rather than return nil values when finding version
  lib/puppet_x/chocolatey/chocolatey_version.rb
Labels: bugfix

#251 pdksync - (MAINT) PDK update for GHA workflows + Litmus updates
  .github/workflows/auto_release.yml
  .github/workflows/nightly.yml
  .github/workflows/pr_test.yml
  metadata.json
Labels: maintenance
